// Code generated by protoc-gen-go.
// source: RegMessage.proto
// DO NOT EDIT!

package example

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type RegMessage struct {
	Id               *int32  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Username         *string `protobuf:"bytes,2,req,name=username" json:"username,omitempty"`
	Password         *string `protobuf:"bytes,3,req,name=password" json:"password,omitempty"`
	Email            *string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RegMessage) Reset()                    { *m = RegMessage{} }
func (m *RegMessage) String() string            { return proto.CompactTextString(m) }
func (*RegMessage) ProtoMessage()               {}
func (*RegMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RegMessage) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *RegMessage) GetUsername() string {
	if m != nil && m.Username != nil {
		return *m.Username
	}
	return ""
}

func (m *RegMessage) GetPassword() string {
	if m != nil && m.Password != nil {
		return *m.Password
	}
	return ""
}

func (m *RegMessage) GetEmail() string {
	if m != nil && m.Email != nil {
		return *m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*RegMessage)(nil), "example.RegMessage")
}

var fileDescriptor1 = []byte{
	// 114 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x08, 0x4a, 0x4d, 0xf7,
	0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4f, 0xad,
	0x48, 0xcc, 0x2d, 0xc8, 0x49, 0x55, 0xf2, 0xe6, 0xe2, 0x42, 0x48, 0x0a, 0x71, 0x71, 0x31, 0x65,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x69, 0xb0, 0x0a, 0x09, 0x70, 0x71, 0x94, 0x16, 0xa7, 0x16, 0xe5,
	0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x01, 0x45, 0x38, 0x41, 0x22, 0x05, 0x89, 0xc5, 0xc5, 0xe5, 0xf9,
	0x45, 0x29, 0x12, 0xcc, 0x60, 0x11, 0x5e, 0x2e, 0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x16,
	0x05, 0x46, 0x0d, 0x4e, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x96, 0xea, 0x35, 0xe8, 0x68, 0x00,
	0x00, 0x00,
}
