// Code generated by protoc-gen-go.
// source: RegMessage.proto
// DO NOT EDIT!

package main

import (
    "net"
    "fmt"
    "os"
    proto "github.com/golang/protobuf/proto"
    "github.com/logoocc/protobuf_example/example"
)


func main() {
    regMessage := &example.RegMessage{
        Id:       proto.Int32(10001),
        Username: proto.String("vicky"),
        Password: proto.String("123456"),
        Email:    proto.String("eclipser@163.com"),
    }

    fmt.Println(regMessage)

    buffer, err := proto.Marshal(regMessage)
    if err != nil {
        fmt.Printf("failed: %s\n", err)
        return
    }


    pTCPAddr, err := net.ResolveTCPAddr("tcp", "127.0.0.1:10000")
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error: %s", err.Error())
        return
    }
    pTCPConn, err := net.DialTCP("tcp", nil, pTCPAddr)
    if err != nil {
        fmt.Fprintf(os.Stderr, "Error: %s", err.Error())
        return
    }
    pTCPConn.Write(buffer)
}